steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest'
      - '--set-secrets'
      - 'OPENAI_API_KEY=OPENAI_API_KEY:latest'
      - '--set-secrets'
      - 'PINECONE_API_KEY=PINECONE_API_KEY:latest'
      - '--set-secrets'
      - 'PINECONE_ENVIRONMENT=PINECONE_ENVIRONMENT:latest'
      - '--set-secrets'
      - 'PINECONE_INDEX_NAME=PINECONE_INDEX_NAME:latest'
      - '--set-secrets'
      - 'PINECONE_NAMESPACE=PINECONE_NAMESPACE:latest'
      - '--set-secrets'
      - 'HANDIT_API_KEY=HANDIT_API_KEY:latest'
      - '--set-secrets'
      - 'DB_HOST=DB_HOST:latest'
      - '--set-secrets'
      - 'DB_PORT=DB_PORT:latest'
      - '--set-secrets'
      - 'DB_NAME=DB_NAME:latest'
      - '--set-secrets'
      - 'DB_USER=DB_USER:latest'
      - '--set-secrets'
      - 'DB_PASSWORD=DB_PASSWORD:latest'
      - '--network=default'
      - '--subnet=default'
      - '--platform=managed'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-env-vars=NODE_OPTIONS=--max-old-space-size=1536'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: handit-ai-docs-agent
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _TRIGGER_ID: '' # This will be populated by Cloud Build
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - handit-ai-docs-agent 